
services:
  frontend:
    build: ./client/inspiQuotes
    ports:
      - "5555:5555"
    networks:
      - inspiQuotes-network
    depends_on:
      - backend
      - mongo
    

  backend:
    build: /server
    ports:
      - "3444:3444"
    depends_on:
      - mongo
    networks:
      - inspiQuotes-network

  mongo:
    image: mongo:latest
    networks:
      - inspiQuotes-network
  
networks:
  inspiQuotes-network:
    driver: bridge


